PostMinePlayback preference
killergerbah/asbplayer pull request #415
Opened 2024-05-05 18:42 UTC by artjomsR

2024-05-05 23:02 UTC, killergerbah requested changes

2024-05-05 23:02 UTC, killergerbah commented on common/settings/settings.ts
> +    readonly clickToMineDefaultPlayback: PostMinePlayback;
Looking at this now the settings categorization does seem somewhat arbitrary but I think I would still prefer for this setting to be under `MiscSettings`.

2024-05-05 23:02 UTC, killergerbah commented on common/settings/settings.ts
> +    readonly clickToMineDefaultPlayback: PostMinePlayback;
I would name this setting something else since it applies even when not clicking to mine.

2024-05-09 04:43 UTC, killergerbah approved these changes

2024-05-10 22:36 UTC, merged

2024-05-10 22:36 UTC, killergerbah commented
Thanks as always @artjomsR

2024-05-10 22:48 UTC, artjomsR commented
Always a pleasure, thanks for your hard work on this beautiful project!