Readme: update dictionaries and regex sections
killergerbah/asbplayer pull request #477
Opened 2024-07-28 23:00 UTC by artjomsR

A couple of small things that I spotted. Please feel free to amend / delete sections that you think aren't relevant.

I've also thought about git-adding the binary file for the go proxy in the repo. This would replace the 1st two steps in the One-click mining flow section (we can leave the original instructions below if someone still wants to compile it themselves). But the disadvantage is that these should be regenerated if the script contents changes, and it's difficult to provide these for all 3 OSes (not sure if you'd want PRs for these as it's kinda a security risk?). Still, if you have a Mac and you include the Mac binary, then you save Mac users a bit of hassle :)

2024-08-02 03:07 UTC, killergerbah requested changes

2024-08-02 03:07 UTC, killergerbah commented on README.md
> +    - `^[\(\)\.\sA-ZAÂÃÀÇÉÊÍÓÔÕÚÑ]+$` : As an alternative to the above, filter out descriptions written in capital letters but without the square brackets, you descriptions that appear in capital let
> you descriptions that appear in capital letters

Typo? I can't make out what this is supposed to say.

2024-08-02 03:07 UTC, killergerbah commented on README.md
> +The proxy is very lightweight, so it's fine to leave it running in the background. On Windows, `RBTray` can be used to minimise it to the taskbar.
Link to RBTray? For convenience.

2024-08-02 03:11 UTC, killergerbah commented
> I've also thought about git-adding the binary file for the go proxy in the repo. 

This is a nice idea. Users would not have to download Go.

>But the disadvantage is that these should be regenerated if the script contents changes, and it's difficult to provide these for all 3 OSes (not sure if you'd want PRs for these as it's kinda a security risk?).

If we can automate the building of all binaries using a script tracked in this repo I think that alleviates some security risk. I would go farther to say that the binaries should not be checked in until we've found a way to automated the build process.

2024-08-02 22:21 UTC, killergerbah commented
Thanks for your changes. I have a final nitpick: "e.g." should be used when listing examples of things, not "i.e.

2024-08-03 08:57 UTC, artjomsR commented
I've also thought so but originally decided to stick to i.e. for consistency :) Updated them now. Also probably a good idea to squash all these commits when you merge this PR

2024-08-04 03:23 UTC, killergerbah commented
Okay awesome. Thanks again for all your contributions.

2024-08-04 03:24 UTC, merged